var annotated_dup =
[
    [ "Catch", "namespaceCatch.html", [
      [ "Detail", "namespaceCatch_1_1Detail.html", [
        [ "Approx", "classCatch_1_1Detail_1_1Approx.html", "classCatch_1_1Detail_1_1Approx" ],
        [ "EnumInfo", "structCatch_1_1Detail_1_1EnumInfo.html", "structCatch_1_1Detail_1_1EnumInfo" ],
        [ "IsStreamInsertable", "classCatch_1_1Detail_1_1IsStreamInsertable.html", null ]
      ] ],
      [ "detail", "namespaceCatch_1_1detail.html", [
        [ "is_range_impl", "structCatch_1_1detail_1_1is__range__impl.html", null ],
        [ "is_range_impl< T, typename void_type< decltype(begin(std::declval< T >()))>::type >", "structCatch_1_1detail_1_1is__range__impl_3_01T_00_01typename_01void__type_3_01decltype_07begin_0efe009a05f00a00c1e4e06989d122a22.html", null ],
        [ "void_type", "structCatch_1_1detail_1_1void__type.html", "structCatch_1_1detail_1_1void__type" ]
      ] ],
      [ "Generators", "namespaceCatch_1_1Generators.html", [
        [ "as", "structCatch_1_1Generators_1_1as.html", null ],
        [ "ChunkGenerator", "classCatch_1_1Generators_1_1ChunkGenerator.html", "classCatch_1_1Generators_1_1ChunkGenerator" ],
        [ "FilterGenerator", "classCatch_1_1Generators_1_1FilterGenerator.html", "classCatch_1_1Generators_1_1FilterGenerator" ],
        [ "FixedValuesGenerator", "classCatch_1_1Generators_1_1FixedValuesGenerator.html", "classCatch_1_1Generators_1_1FixedValuesGenerator" ],
        [ "Generators", "classCatch_1_1Generators_1_1Generators.html", "classCatch_1_1Generators_1_1Generators" ],
        [ "GeneratorUntypedBase", "classCatch_1_1Generators_1_1GeneratorUntypedBase.html", "classCatch_1_1Generators_1_1GeneratorUntypedBase" ],
        [ "GeneratorWrapper", "classCatch_1_1Generators_1_1GeneratorWrapper.html", "classCatch_1_1Generators_1_1GeneratorWrapper" ],
        [ "IGenerator", "structCatch_1_1Generators_1_1IGenerator.html", "structCatch_1_1Generators_1_1IGenerator" ],
        [ "MapGenerator", "classCatch_1_1Generators_1_1MapGenerator.html", "classCatch_1_1Generators_1_1MapGenerator" ],
        [ "RepeatGenerator", "classCatch_1_1Generators_1_1RepeatGenerator.html", "classCatch_1_1Generators_1_1RepeatGenerator" ],
        [ "SingleValueGenerator", "classCatch_1_1Generators_1_1SingleValueGenerator.html", "classCatch_1_1Generators_1_1SingleValueGenerator" ],
        [ "TakeGenerator", "classCatch_1_1Generators_1_1TakeGenerator.html", "classCatch_1_1Generators_1_1TakeGenerator" ]
      ] ],
      [ "Matchers", "namespaceCatch_1_1Matchers.html", [
        [ "Exception", "namespaceCatch_1_1Matchers_1_1Exception.html", [
          [ "ExceptionMessageMatcher", "classCatch_1_1Matchers_1_1Exception_1_1ExceptionMessageMatcher.html", "classCatch_1_1Matchers_1_1Exception_1_1ExceptionMessageMatcher" ]
        ] ],
        [ "Floating", "namespaceCatch_1_1Matchers_1_1Floating.html", [
          [ "WithinAbsMatcher", "structCatch_1_1Matchers_1_1Floating_1_1WithinAbsMatcher.html", "structCatch_1_1Matchers_1_1Floating_1_1WithinAbsMatcher" ],
          [ "WithinRelMatcher", "structCatch_1_1Matchers_1_1Floating_1_1WithinRelMatcher.html", "structCatch_1_1Matchers_1_1Floating_1_1WithinRelMatcher" ],
          [ "WithinUlpsMatcher", "structCatch_1_1Matchers_1_1Floating_1_1WithinUlpsMatcher.html", "structCatch_1_1Matchers_1_1Floating_1_1WithinUlpsMatcher" ]
        ] ],
        [ "Impl", "namespaceCatch_1_1Matchers_1_1Impl.html", [
          [ "MatchAllOf", "structCatch_1_1Matchers_1_1Impl_1_1MatchAllOf.html", "structCatch_1_1Matchers_1_1Impl_1_1MatchAllOf" ],
          [ "MatchAnyOf", "structCatch_1_1Matchers_1_1Impl_1_1MatchAnyOf.html", "structCatch_1_1Matchers_1_1Impl_1_1MatchAnyOf" ],
          [ "MatcherBase", "structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html", "structCatch_1_1Matchers_1_1Impl_1_1MatcherBase" ],
          [ "MatcherMethod", "structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html", "structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod" ],
          [ "MatcherUntypedBase", "classCatch_1_1Matchers_1_1Impl_1_1MatcherUntypedBase.html", "classCatch_1_1Matchers_1_1Impl_1_1MatcherUntypedBase" ],
          [ "MatchNotOf", "structCatch_1_1Matchers_1_1Impl_1_1MatchNotOf.html", "structCatch_1_1Matchers_1_1Impl_1_1MatchNotOf" ]
        ] ],
        [ "StdString", "namespaceCatch_1_1Matchers_1_1StdString.html", [
          [ "CasedString", "structCatch_1_1Matchers_1_1StdString_1_1CasedString.html", "structCatch_1_1Matchers_1_1StdString_1_1CasedString" ],
          [ "ContainsMatcher", "structCatch_1_1Matchers_1_1StdString_1_1ContainsMatcher.html", "structCatch_1_1Matchers_1_1StdString_1_1ContainsMatcher" ],
          [ "EndsWithMatcher", "structCatch_1_1Matchers_1_1StdString_1_1EndsWithMatcher.html", "structCatch_1_1Matchers_1_1StdString_1_1EndsWithMatcher" ],
          [ "EqualsMatcher", "structCatch_1_1Matchers_1_1StdString_1_1EqualsMatcher.html", "structCatch_1_1Matchers_1_1StdString_1_1EqualsMatcher" ],
          [ "RegexMatcher", "structCatch_1_1Matchers_1_1StdString_1_1RegexMatcher.html", "structCatch_1_1Matchers_1_1StdString_1_1RegexMatcher" ],
          [ "StartsWithMatcher", "structCatch_1_1Matchers_1_1StdString_1_1StartsWithMatcher.html", "structCatch_1_1Matchers_1_1StdString_1_1StartsWithMatcher" ],
          [ "StringMatcherBase", "structCatch_1_1Matchers_1_1StdString_1_1StringMatcherBase.html", "structCatch_1_1Matchers_1_1StdString_1_1StringMatcherBase" ]
        ] ]
      ] ],
      [ "always_false", "structCatch_1_1always__false.html", null ],
      [ "AssertionHandler", "classCatch_1_1AssertionHandler.html", "classCatch_1_1AssertionHandler" ],
      [ "AssertionInfo", "structCatch_1_1AssertionInfo.html", "structCatch_1_1AssertionInfo" ],
      [ "AssertionReaction", "structCatch_1_1AssertionReaction.html", "structCatch_1_1AssertionReaction" ],
      [ "AutoReg", "structCatch_1_1AutoReg.html", "structCatch_1_1AutoReg" ],
      [ "BinaryExpr", "classCatch_1_1BinaryExpr.html", "classCatch_1_1BinaryExpr" ],
      [ "Capturer", "classCatch_1_1Capturer.html", "classCatch_1_1Capturer" ],
      [ "CaseSensitive", "structCatch_1_1CaseSensitive.html", "structCatch_1_1CaseSensitive" ],
      [ "Counts", "structCatch_1_1Counts.html", "structCatch_1_1Counts" ],
      [ "Decomposer", "structCatch_1_1Decomposer.html", "structCatch_1_1Decomposer" ],
      [ "ExceptionTranslatorRegistrar", "classCatch_1_1ExceptionTranslatorRegistrar.html", "classCatch_1_1ExceptionTranslatorRegistrar" ],
      [ "ExprLhs", "classCatch_1_1ExprLhs.html", "classCatch_1_1ExprLhs" ],
      [ "GeneratorException", "classCatch_1_1GeneratorException.html", "classCatch_1_1GeneratorException" ],
      [ "IContext", "structCatch_1_1IContext.html", "structCatch_1_1IContext" ],
      [ "IExceptionTranslator", "structCatch_1_1IExceptionTranslator.html", "structCatch_1_1IExceptionTranslator" ],
      [ "IExceptionTranslatorRegistry", "structCatch_1_1IExceptionTranslatorRegistry.html", "structCatch_1_1IExceptionTranslatorRegistry" ],
      [ "IGeneratorTracker", "structCatch_1_1IGeneratorTracker.html", "structCatch_1_1IGeneratorTracker" ],
      [ "IMutableContext", "structCatch_1_1IMutableContext.html", "structCatch_1_1IMutableContext" ],
      [ "IMutableEnumValuesRegistry", "structCatch_1_1IMutableEnumValuesRegistry.html", "structCatch_1_1IMutableEnumValuesRegistry" ],
      [ "IResultCapture", "structCatch_1_1IResultCapture.html", "structCatch_1_1IResultCapture" ],
      [ "is_callable", "structCatch_1_1is__callable.html", null ],
      [ "is_callable< Fun(Args...)>", "structCatch_1_1is__callable_3_01Fun_07Args_8_8_8_08_4.html", null ],
      [ "is_callable_tester", "structCatch_1_1is__callable__tester.html", null ],
      [ "is_range", "structCatch_1_1is__range.html", null ],
      [ "IStream", "structCatch_1_1IStream.html", "structCatch_1_1IStream" ],
      [ "ITestCaseRegistry", "structCatch_1_1ITestCaseRegistry.html", "structCatch_1_1ITestCaseRegistry" ],
      [ "ITestInvoker", "structCatch_1_1ITestInvoker.html", "structCatch_1_1ITestInvoker" ],
      [ "ITransientExpression", "structCatch_1_1ITransientExpression.html", "structCatch_1_1ITransientExpression" ],
      [ "LazyExpression", "classCatch_1_1LazyExpression.html", "classCatch_1_1LazyExpression" ],
      [ "MessageBuilder", "structCatch_1_1MessageBuilder.html", "structCatch_1_1MessageBuilder" ],
      [ "MessageInfo", "structCatch_1_1MessageInfo.html", "structCatch_1_1MessageInfo" ],
      [ "MessageStream", "structCatch_1_1MessageStream.html", "structCatch_1_1MessageStream" ],
      [ "NameAndTags", "structCatch_1_1NameAndTags.html", "structCatch_1_1NameAndTags" ],
      [ "NonCopyable", "classCatch_1_1NonCopyable.html", "classCatch_1_1NonCopyable" ],
      [ "pluralise", "structCatch_1_1pluralise.html", "structCatch_1_1pluralise" ],
      [ "RegistrarForTagAliases", "structCatch_1_1RegistrarForTagAliases.html", "structCatch_1_1RegistrarForTagAliases" ],
      [ "ResultDisposition", "structCatch_1_1ResultDisposition.html", "structCatch_1_1ResultDisposition" ],
      [ "ResultWas", "structCatch_1_1ResultWas.html", "structCatch_1_1ResultWas" ],
      [ "ReusableStringStream", "classCatch_1_1ReusableStringStream.html", "classCatch_1_1ReusableStringStream" ],
      [ "ScopedMessage", "classCatch_1_1ScopedMessage.html", "classCatch_1_1ScopedMessage" ],
      [ "Section", "classCatch_1_1Section.html", "classCatch_1_1Section" ],
      [ "SectionEndInfo", "structCatch_1_1SectionEndInfo.html", "structCatch_1_1SectionEndInfo" ],
      [ "SectionInfo", "structCatch_1_1SectionInfo.html", "structCatch_1_1SectionInfo" ],
      [ "SimplePcg32", "classCatch_1_1SimplePcg32.html", "classCatch_1_1SimplePcg32" ],
      [ "SourceLineInfo", "structCatch_1_1SourceLineInfo.html", "structCatch_1_1SourceLineInfo" ],
      [ "StreamEndStop", "structCatch_1_1StreamEndStop.html", "structCatch_1_1StreamEndStop" ],
      [ "StringMaker", "structCatch_1_1StringMaker.html", null ],
      [ "StringMaker< bool >", "structCatch_1_1StringMaker_3_01bool_01_4.html", null ],
      [ "StringMaker< Catch::Detail::Approx >", "structCatch_1_1StringMaker_3_01Catch_1_1Detail_1_1Approx_01_4.html", null ],
      [ "StringMaker< char * >", "structCatch_1_1StringMaker_3_01char_01_5_01_4.html", null ],
      [ "StringMaker< char >", "structCatch_1_1StringMaker_3_01char_01_4.html", null ],
      [ "StringMaker< char const * >", "structCatch_1_1StringMaker_3_01char_01const_01_5_01_4.html", null ],
      [ "StringMaker< char[SZ]>", "structCatch_1_1StringMaker_3_01char_0fSZ_0e_4.html", null ],
      [ "StringMaker< double >", "structCatch_1_1StringMaker_3_01double_01_4.html", null ],
      [ "StringMaker< float >", "structCatch_1_1StringMaker_3_01float_01_4.html", null ],
      [ "StringMaker< int >", "structCatch_1_1StringMaker_3_01int_01_4.html", null ],
      [ "StringMaker< long >", "structCatch_1_1StringMaker_3_01long_01_4.html", null ],
      [ "StringMaker< long long >", "structCatch_1_1StringMaker_3_01long_01long_01_4.html", null ],
      [ "StringMaker< R C::* >", "structCatch_1_1StringMaker_3_01R_01C_1_1_5_01_4.html", null ],
      [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "structCatch_1_1StringMaker_3_01R_00_01typename_01std_1_1enable__if_3_01is__range_3_01R_01_4_1_1ve8233c20b54b69b4771fbd413409d181.html", null ],
      [ "StringMaker< signed char >", "structCatch_1_1StringMaker_3_01signed_01char_01_4.html", null ],
      [ "StringMaker< signed char[SZ]>", "structCatch_1_1StringMaker_3_01signed_01char_0fSZ_0e_4.html", null ],
      [ "StringMaker< std::nullptr_t >", "structCatch_1_1StringMaker_3_01std_1_1nullptr__t_01_4.html", null ],
      [ "StringMaker< std::string >", "structCatch_1_1StringMaker_3_01std_1_1string_01_4.html", null ],
      [ "StringMaker< std::wstring >", "structCatch_1_1StringMaker_3_01std_1_1wstring_01_4.html", null ],
      [ "StringMaker< T * >", "structCatch_1_1StringMaker_3_01T_01_5_01_4.html", null ],
      [ "StringMaker< T[SZ]>", "structCatch_1_1StringMaker_3_01T_0fSZ_0e_4.html", null ],
      [ "StringMaker< unsigned char >", "structCatch_1_1StringMaker_3_01unsigned_01char_01_4.html", null ],
      [ "StringMaker< unsigned char[SZ]>", "structCatch_1_1StringMaker_3_01unsigned_01char_0fSZ_0e_4.html", null ],
      [ "StringMaker< unsigned int >", "structCatch_1_1StringMaker_3_01unsigned_01int_01_4.html", null ],
      [ "StringMaker< unsigned long >", "structCatch_1_1StringMaker_3_01unsigned_01long_01_4.html", null ],
      [ "StringMaker< unsigned long long >", "structCatch_1_1StringMaker_3_01unsigned_01long_01long_01_4.html", null ],
      [ "StringMaker< wchar_t * >", "structCatch_1_1StringMaker_3_01wchar__t_01_5_01_4.html", null ],
      [ "StringMaker< wchar_t const * >", "structCatch_1_1StringMaker_3_01wchar__t_01const_01_5_01_4.html", null ],
      [ "StringRef", "classCatch_1_1StringRef.html", "classCatch_1_1StringRef" ],
      [ "TestCase", "classCatch_1_1TestCase.html", "classCatch_1_1TestCase" ],
      [ "TestCaseInfo", "structCatch_1_1TestCaseInfo.html", "structCatch_1_1TestCaseInfo" ],
      [ "TestFailureException", "structCatch_1_1TestFailureException.html", null ],
      [ "TestInvokerAsMethod", "classCatch_1_1TestInvokerAsMethod.html", "classCatch_1_1TestInvokerAsMethod" ],
      [ "Timer", "classCatch_1_1Timer.html", "classCatch_1_1Timer" ],
      [ "Totals", "structCatch_1_1Totals.html", "structCatch_1_1Totals" ],
      [ "true_given", "structCatch_1_1true__given.html", null ],
      [ "UnaryExpr", "classCatch_1_1UnaryExpr.html", "classCatch_1_1UnaryExpr" ]
    ] ],
    [ "Catch_global_namespace_dummy", "structCatch__global__namespace__dummy.html", null ],
    [ "Matrix", "classMatrix.html", "classMatrix" ]
];